# Generated by Django 4.2.3 on 2023-12-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0011_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_price',
            field=models.IntegerField(default=0, help_text='환불된 금액'),
        ),
        migrations.AddField(
            model_name='orderfoodproductrelation',
            name='refund_quantity',
            field=models.IntegerField(default=0, help_text='환불완료된 상품 개수'),
        ),
        migrations.AddField(
            model_name='orderfoodproductrelation',
            name='refund_request_quantity',
            field=models.IntegerField(default=0, help_text='환불요청 하려는 상품 개수'),
        ),
        migrations.CreateModel(
            name='OrderRefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('content', models.TextField()),
                ('pg_uid', models.CharField(help_text='PG사 승인번호', max_length=100)),
                ('refunded_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_refund_logs', to='app_model.order')),
            ],
        ),
    ]
