# list of Dutch circumpositions
circumpositions = [
    ('aan', 'toe'),
    ('achter', 'aan'),
    ('bij',  'af'),
    ('bij', 'na'),
    ('bij', 'thuis'),
    ('bij', 'vandaan'),
    ('boven', 'uit'),
    ('buiten', 'om'),
    ('door', 'heen'),
    ('met', 'mee'),
    ('naar', 'toe'),
    ('om', 'heen'),
    ('onder', 'door'),
    ('onder', ' uit'),
    ('onder', 'vandaan'),
    ('op', 'af'),
    ('op', 'na'),
    ('over', 'heen'),
    ('tegen', 'aan'),
    ('tegen', 'in'),
    ('tegen', 'op'),
    ('tot', 'toe'),
    ('tussen', 'door'),
    ('tussen', 'in'),
    ('uit', 'vandaan'),
    ('van', 'af'),
    ('van', 'uit'),
    ('van', 'vandaan'),
    ('voor', 'aan'),
    ('voor', 'langs'),
    ('voor', 'uit')
]

vzazindex = {vz+az: (vz, az) for (vz, az) in circumpositions}
