# generated by datamodel-codegen:
#   filename:  placement.json
#   timestamp: 2023-12-20T14:05:47+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Position: List[float] = Field(..., description='Position of the Placement')
    Axis: List[float] = Field(..., description='Axis of the Placement')
    Angle: float = Field(..., description='Angle of the Placement')
