from looqbox.class_loader.lazy_load import LazyLoad
from looqbox.objects.component_utility.css_option import CssOption


@LazyLoad
class ObjMessage: ...
@LazyLoad
class ObjImage: ...
@LazyLoad
class ObjVideo: ...
@LazyLoad
class ObjList: ...
@LazyLoad
class ObjHTML: ...
@LazyLoad
class ObjPDF: ...
@LazyLoad
class ObjWebFrame: ...
@LazyLoad
class ObjTable: ...
@LazyLoad
class ObjPlotly: ...
@LazyLoad
class ObjForm: ...
@LazyLoad
class ObjImageCapture: ...
@LazyLoad
class ObjEmbed: ...
@LazyLoad
class ObjText: ...
@LazyLoad
class ObjSimple: ...
@LazyLoad
class ObjFormHTML: ...
@LazyLoad
class ObjRow: ...
@LazyLoad
class ObjColumn: ...
@LazyLoad
class ObjSwitch: ...
@LazyLoad
class ObjQuery: ...
@LazyLoad
class ObjTooltip: ...
@LazyLoad
class ObjLink: ...
@LazyLoad
class ObjGauge: ...
@LazyLoad
class ObjLine: ...
@LazyLoad
class ObjFileUpload: ...
@LazyLoad
class ObjAudio: ...


__all__ = ["ObjTable", "ObjWebFrame", "ObjPlotly", "ObjPDF", "ObjList", "ObjHTML", "ObjImage",
           "ObjMessage", "ObjVideo", "ObjForm", "ObjFileUpload", "ObjImageCapture", "ObjEmbed",
           "ObjAudio", "ObjSimple", "ObjFormHTML", "ObjQuery", "ObjRow", "ObjColumn", "ObjSwitch",
           "ObjTooltip", "ObjLink", "ObjText", "ObjGauge", "ObjLine", "CssOption"]
