
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-21T13:49:11+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "651513c44bd64097220b337288d5f6cbcd242915",
 "version": "0.8.0.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
