# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.pin_update_request_dto import PinUpdateRequestDTO  # noqa: E501

class TestPinUpdateRequestDTO(unittest.TestCase):
    """PinUpdateRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PinUpdateRequestDTO:
        """Test PinUpdateRequestDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PinUpdateRequestDTO`
        """
        model = PinUpdateRequestDTO()  # noqa: E501
        if include_optional:
            return PinUpdateRequestDTO(
                pin_block = 'MTA0NzM='
            )
        else:
            return PinUpdateRequestDTO(
                pin_block = 'MTA0NzM=',
        )
        """

    def testPinUpdateRequestDTO(self):
        """Test PinUpdateRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
