# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.business_address import BusinessAddress  # noqa: E501

class TestBusinessAddress(unittest.TestCase):
    """BusinessAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BusinessAddress:
        """Test BusinessAddress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BusinessAddress`
        """
        model = BusinessAddress()  # noqa: E501
        if include_optional:
            return BusinessAddress(
                address_line1 = '',
                address_line2 = '',
                city = '',
                country = '',
                postcode = '',
                state = ''
            )
        else:
            return BusinessAddress(
        )
        """

    def testBusinessAddress(self):
        """Test BusinessAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
