# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.exchange_rate_v2_response_dto import ExchangeRateV2ResponseDto  # noqa: E501

class TestExchangeRateV2ResponseDto(unittest.TestCase):
    """ExchangeRateV2ResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExchangeRateV2ResponseDto:
        """Test ExchangeRateV2ResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExchangeRateV2ResponseDto`
        """
        model = ExchangeRateV2ResponseDto()  # noqa: E501
        if include_optional:
            return ExchangeRateV2ResponseDto(
                destination_amount = 13.42,
                destination_currency_code = 'SGD',
                ecb_fx_rate = 1.349,
                exchange_rate = 1.349,
                expiry_date = '2021-03-09T06:46:03.000Z',
                markup_amount = 0.07,
                markup_rate = 0.006745,
                net_exchange_rate = 1.342255,
                quote_id = 'f3632302-1d41-4a40-b7a0-4c456dddbd9e',
                scaling_factor = 1,
                source_amount = 10,
                source_currency_code = 'USD'
            )
        else:
            return ExchangeRateV2ResponseDto(
        )
        """

    def testExchangeRateV2ResponseDto(self):
        """Test ExchangeRateV2ResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
