# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.bank_account_details import BankAccountDetails  # noqa: E501

class TestBankAccountDetails(unittest.TestCase):
    """BankAccountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankAccountDetails:
        """Test BankAccountDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankAccountDetails`
        """
        model = BankAccountDetails()  # noqa: E501
        if include_optional:
            return BankAccountDetails(
                account_name = '',
                account_number = '',
                bank_name = '',
                currency = '',
                routing_type = '',
                routing_value = ''
            )
        else:
            return BankAccountDetails(
        )
        """

    def testBankAccountDetails(self):
        """Test BankAccountDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
