# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.merchant_category_response_dto2 import MerchantCategoryResponseDTO2  # noqa: E501

class TestMerchantCategoryResponseDTO2(unittest.TestCase):
    """MerchantCategoryResponseDTO2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantCategoryResponseDTO2:
        """Test MerchantCategoryResponseDTO2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantCategoryResponseDTO2`
        """
        model = MerchantCategoryResponseDTO2()  # noqa: E501
        if include_optional:
            return MerchantCategoryResponseDTO2(
                description = 'Ice cream shops, Fast Food Restaurants',
                mcc_code = '5814',
                merchant_category = 'Food n Beverage'
            )
        else:
            return MerchantCategoryResponseDTO2(
        )
        """

    def testMerchantCategoryResponseDTO2(self):
        """Test MerchantCategoryResponseDTO2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
