# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.error_response403 import ErrorResponse403  # noqa: E501

class TestErrorResponse403(unittest.TestCase):
    """ErrorResponse403 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponse403:
        """Test ErrorResponse403
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponse403`
        """
        model = ErrorResponse403()  # noqa: E501
        if include_optional:
            return ErrorResponse403(
                error_details = [
                    nium.models.error_detail403.ErrorDetail403(
                        code = 'fx_client_no_access', 
                        description = '', )
                    ]
            )
        else:
            return ErrorResponse403(
        )
        """

    def testErrorResponse403(self):
        """Test ErrorResponse403"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
