# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.individual_customer_response_dto import IndividualCustomerResponseDTO  # noqa: E501

class TestIndividualCustomerResponseDTO(unittest.TestCase):
    """IndividualCustomerResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndividualCustomerResponseDTO:
        """Test IndividualCustomerResponseDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndividualCustomerResponseDTO`
        """
        model = IndividualCustomerResponseDTO()  # noqa: E501
        if include_optional:
            return IndividualCustomerResponseDTO(
                billing_address1 = '',
                billing_address2 = 'Johnson Square',
                billing_city = 'Sydney',
                billing_country = 'AU',
                billing_landmark = 'null',
                billing_state = 'New South Wales',
                billing_zip_code = '2001',
                country_code = 'AU',
                country_of_birth = 'null',
                date_of_birth = '1992-08-09',
                designation = 'null',
                email = 'xyzabc@abcmail.com',
                employee_id = 'null',
                estimated_monthly_funding = '1000-5000',
                estimated_monthly_funding_currency = 'EUR',
                expected_countries_to_send_receive_from = FR,
                first_name = 'ABCD XYZ',
                gender = 'Male',
                identification_data = [
                    {
                        'key' : ''
                        }
                    ],
                international_payments_supported = True,
                last_name = 'PVT LTD',
                middle_name = 'null',
                mobile = '950030024',
                nationality = 'AU',
                native_language_name = 'null',
                occupation = 'OC0001',
                parent_customer_hash_id = '',
                pep = False,
                preferred_name = 'ABCD XYZ LT',
                tax_details = [
                    nium.models.tax_details_response_dto.TaxDetailsResponseDTO(
                        country = 'France', 
                        tax_number = 'FR123456', )
                    ]
            )
        else:
            return IndividualCustomerResponseDTO(
        )
        """

    def testIndividualCustomerResponseDTO(self):
        """Test IndividualCustomerResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
