# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.error_codes400 import ErrorCodes400  # noqa: E501

class TestErrorCodes400(unittest.TestCase):
    """ErrorCodes400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorCodes400(self):
        """Test ErrorCodes400"""
        # inst = ErrorCodes400()

if __name__ == '__main__':
    unittest.main()
