# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.error_codes500 import ErrorCodes500  # noqa: E501

class TestErrorCodes500(unittest.TestCase):
    """ErrorCodes500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorCodes500(self):
        """Test ErrorCodes500"""
        # inst = ErrorCodes500()

if __name__ == '__main__':
    unittest.main()
