# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.wallet_transfer_response_dto import WalletTransferResponseDto  # noqa: E501

class TestWalletTransferResponseDto(unittest.TestCase):
    """WalletTransferResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletTransferResponseDto:
        """Test WalletTransferResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletTransferResponseDto`
        """
        model = WalletTransferResponseDto()  # noqa: E501
        if include_optional:
            return WalletTransferResponseDto(
                destination_amount = 549.07,
                destination_currency_code = 'INR',
                exchange_rate = 54.934,
                markup_amount = 0.27,
                markup_rate = 0.027467,
                net_exchange_rate = 54.906533,
                scaling_factor = 1,
                source_amount = 10,
                source_currency_code = 'SGD',
                system_reference_number = 'CP2919853847'
            )
        else:
            return WalletTransferResponseDto(
        )
        """

    def testWalletTransferResponseDto(self):
        """Test WalletTransferResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
