# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.client_prefund_response_dto import ClientPrefundResponseDTO  # noqa: E501

class TestClientPrefundResponseDTO(unittest.TestCase):
    """ClientPrefundResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientPrefundResponseDTO:
        """Test ClientPrefundResponseDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientPrefundResponseDTO`
        """
        model = ClientPrefundResponseDTO()  # noqa: E501
        if include_optional:
            return ClientPrefundResponseDTO(
                amount = 1000,
                message = 'Prefund request added successfully',
                status = 'Pending',
                system_reference_number = 'CP8790469553',
                unique_payer_id = 'abc12_ca@nium.com',
                unique_payment_id = '533343532'
            )
        else:
            return ClientPrefundResponseDTO(
        )
        """

    def testClientPrefundResponseDTO(self):
        """Test ClientPrefundResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
