# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.association_details import AssociationDetails  # noqa: E501

class TestAssociationDetails(unittest.TestCase):
    """AssociationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssociationDetails:
        """Test AssociationDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssociationDetails`
        """
        model = AssociationDetails()  # noqa: E501
        if include_optional:
            return AssociationDetails(
                association_chair_person = '',
                association_name = '',
                association_number = ''
            )
        else:
            return AssociationDetails(
        )
        """

    def testAssociationDetails(self):
        """Test AssociationDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
