# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.transactions_location_dto import TransactionsLocationDTO  # noqa: E501

class TestTransactionsLocationDTO(unittest.TestCase):
    """TransactionsLocationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionsLocationDTO:
        """Test TransactionsLocationDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionsLocationDTO`
        """
        model = TransactionsLocationDTO()  # noqa: E501
        if include_optional:
            return TransactionsLocationDTO(
                merchant_latitude = '28.532094',
                merchant_longitude = '77.01632',
                merchant_tagged_name = 'STARBUCKS',
                merchant_zoom_index = '4'
            )
        else:
            return TransactionsLocationDTO(
                merchant_latitude = '28.532094',
                merchant_longitude = '77.01632',
                merchant_tagged_name = 'STARBUCKS',
                merchant_zoom_index = '4',
        )
        """

    def testTransactionsLocationDTO(self):
        """Test TransactionsLocationDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
