# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nium.api.lifecycle_api import LifecycleApi  # noqa: E501


class TestLifecycleApi(unittest.TestCase):
    """LifecycleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LifecycleApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_activate_card(self) -> None:
        """Test case for activate_card

        Activate Card  # noqa: E501
        """
        pass

    def test_activate_card1(self) -> None:
        """Test case for activate_card1

        Activate Card  # noqa: E501
        """
        pass

    def test_add_card(self) -> None:
        """Test case for add_card

        Add Card  # noqa: E501
        """
        pass

    def test_add_card_v2(self) -> None:
        """Test case for add_card_v2

        Add Card V2  # noqa: E501
        """
        pass

    def test_assign_card(self) -> None:
        """Test case for assign_card

        Assign Card  # noqa: E501
        """
        pass

    def test_block_and_replace_card_v2(self) -> None:
        """Test case for block_and_replace_card_v2

        Block and Replace Card V2  # noqa: E501
        """
        pass

    def test_block_unblock_cards(self) -> None:
        """Test case for block_unblock_cards

        Block/Unblock Cards  # noqa: E501
        """
        pass

    def test_card_details(self) -> None:
        """Test case for card_details

        Card Details  # noqa: E501
        """
        pass

    def test_card_details_v2(self) -> None:
        """Test case for card_details_v2

        Card Details V2  # noqa: E501
        """
        pass

    def test_card_list(self) -> None:
        """Test case for card_list

        Card List  # noqa: E501
        """
        pass

    def test_card_list_v2(self) -> None:
        """Test case for card_list_v2

        Card List V2  # noqa: E501
        """
        pass

    def test_get_card_widget(self) -> None:
        """Test case for get_card_widget

        Get Card Details Widget  # noqa: E501
        """
        pass

    def test_issue_replacement_card(self) -> None:
        """Test case for issue_replacement_card

        Issue Replacement Card  # noqa: E501
        """
        pass

    def test_lock_unlock_card_v2(self) -> None:
        """Test case for lock_unlock_card_v2

        Lock/Unlock Card V2  # noqa: E501
        """
        pass

    def test_renew_card(self) -> None:
        """Test case for renew_card

        Renew Card  # noqa: E501
        """
        pass

    def test_update_card_details_v2(self) -> None:
        """Test case for update_card_details_v2

        Update Card Details V2  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
