# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nium.api.security_api import SecurityApi  # noqa: E501


class TestSecurityApi(unittest.TestCase):
    """SecurityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecurityApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_fetch_atm_pin(self) -> None:
        """Test case for fetch_atm_pin

        Fetch ATM Pin  # noqa: E501
        """
        pass

    def test_fetch_card_data_encrypted_v2(self) -> None:
        """Test case for fetch_card_data_encrypted_v2

        Fetch Card Data Encrypted V2  # noqa: E501
        """
        pass

    def test_fetch_cvv2(self) -> None:
        """Test case for fetch_cvv2

        Fetch CVV2  # noqa: E501
        """
        pass

    def test_fetch_pin_status(self) -> None:
        """Test case for fetch_pin_status

        Fetch Pin Status  # noqa: E501
        """
        pass

    def test_set_reset_pin(self) -> None:
        """Test case for set_reset_pin

        Set/Reset PIN  # noqa: E501
        """
        pass

    def test_unblock_card_pin(self) -> None:
        """Test case for unblock_card_pin

        Unblock PIN  # noqa: E501
        """
        pass

    def test_unmask_card(self) -> None:
        """Test case for unmask_card

        Unmask Card  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
