# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.product_partnership_details import ProductPartnershipDetails  # noqa: E501

class TestProductPartnershipDetails(unittest.TestCase):
    """ProductPartnershipDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductPartnershipDetails:
        """Test ProductPartnershipDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductPartnershipDetails`
        """
        model = ProductPartnershipDetails()  # noqa: E501
        if include_optional:
            return ProductPartnershipDetails(
                partner_country = '',
                partner_name = '',
                partner_state = ''
            )
        else:
            return ProductPartnershipDetails(
        )
        """

    def testProductPartnershipDetails(self):
        """Test ProductPartnershipDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
