# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nium.api.cards_reference_data_api import CardsReferenceDataApi  # noqa: E501


class TestCardsReferenceDataApi(unittest.TestCase):
    """CardsReferenceDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CardsReferenceDataApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_reference_exchange_rate(self) -> None:
        """Test case for reference_exchange_rate

        Reference Exchange Rate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
