# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nium.api.conversions_previous_version_api import ConversionsPreviousVersionApi  # noqa: E501


class TestConversionsPreviousVersionApi(unittest.TestCase):
    """ConversionsPreviousVersionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConversionsPreviousVersionApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_balance_transferwithin_wallet(self) -> None:
        """Test case for balance_transferwithin_wallet

        Balance Transfer within Wallet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
