# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.rfi_attribute_response import RfiAttributeResponse  # noqa: E501

class TestRfiAttributeResponse(unittest.TestCase):
    """RfiAttributeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RfiAttributeResponse:
        """Test RfiAttributeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RfiAttributeResponse`
        """
        model = RfiAttributeResponse()  # noqa: E501
        if include_optional:
            return RfiAttributeResponse(
                label = 'Date Of Birth',
                type = 'data',
                value = 'dateOfBirth'
            )
        else:
            return RfiAttributeResponse(
        )
        """

    def testRfiAttributeResponse(self):
        """Test RfiAttributeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
