# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.fetch_pin_status_response_dto import FetchPinStatusResponseDTO  # noqa: E501

class TestFetchPinStatusResponseDTO(unittest.TestCase):
    """FetchPinStatusResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchPinStatusResponseDTO:
        """Test FetchPinStatusResponseDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchPinStatusResponseDTO`
        """
        model = FetchPinStatusResponseDTO()  # noqa: E501
        if include_optional:
            return FetchPinStatusResponseDTO(
                status = ''
            )
        else:
            return FetchPinStatusResponseDTO(
        )
        """

    def testFetchPinStatusResponseDTO(self):
        """Test FetchPinStatusResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
