# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nium.api.customer_management_api import CustomerManagementApi  # noqa: E501


class TestCustomerManagementApi(unittest.TestCase):
    """CustomerManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomerManagementApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_account_statement(self) -> None:
        """Test case for account_statement

        Account Statement  # noqa: E501
        """
        pass

    def test_block_unblock_customer(self) -> None:
        """Test case for block_unblock_customer

        Block/Unblock Customer  # noqa: E501
        """
        pass

    def test_customer_details(self) -> None:
        """Test case for customer_details

        Customer Details  # noqa: E501
        """
        pass

    def test_customer_details_v2(self) -> None:
        """Test case for customer_details_v2

        Customer Details V2  # noqa: E501
        """
        pass

    def test_customer_list(self) -> None:
        """Test case for customer_list

        Customer List  # noqa: E501
        """
        pass

    def test_customer_list_v2(self) -> None:
        """Test case for customer_list_v2

        Get Paginated Customer By Client And Optional Search Parameters.  # noqa: E501
        """
        pass

    def test_customer_list_v3(self) -> None:
        """Test case for customer_list_v3

        Get Paginated Customer By Client And Optional Search Parameters.  # noqa: E501
        """
        pass

    def test_manage_customer_tags(self) -> None:
        """Test case for manage_customer_tags

        Manage Customer Tags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
