# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nium.api.open_banking_onboarding_api import OpenBankingOnboardingApi  # noqa: E501


class TestOpenBankingOnboardingApi(unittest.TestCase):
    """OpenBankingOnboardingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenBankingOnboardingApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_account_details_by_customer_consent_id(self) -> None:
        """Test case for account_details_by_customer_consent_id

        Account Details By Customer Consent ID.  # noqa: E501
        """
        pass

    def test_payment_detailsby_system_reference_number(self) -> None:
        """Test case for payment_detailsby_system_reference_number

        Payment Details by System Reference Number  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
