# coding: utf-8

"""
    NIUM Platform

    NIUM Platform

    The version of the OpenAPI document: 2023.12.5
    Contact: experience@nium.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nium.models.upload_rfi_details_response_dto import UploadRfiDetailsResponseDto  # noqa: E501

class TestUploadRfiDetailsResponseDto(unittest.TestCase):
    """UploadRfiDetailsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadRfiDetailsResponseDto:
        """Test UploadRfiDetailsResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadRfiDetailsResponseDto`
        """
        model = UploadRfiDetailsResponseDto()  # noqa: E501
        if include_optional:
            return UploadRfiDetailsResponseDto(
                compliance_id = '',
                rfi_id = '',
                status = ''
            )
        else:
            return UploadRfiDetailsResponseDto(
        )
        """

    def testUploadRfiDetailsResponseDto(self):
        """Test UploadRfiDetailsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
