# Generated by Django 4.2.3 on 2023-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0012_order_refunded_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iamportcancellog',
            name='refunded_price',
            field=models.IntegerField(default=0, help_text='환불된 금액'),
        ),
        migrations.AddField(
            model_name='iamportorder',
            name='refunded_price',
            field=models.IntegerField(default=0, help_text='환불된 금액'),
        ),
    ]
