__title__ = "citros"
__description__ = "citros"
__url__ = "https://citros.io"
__version__ = "0.0.21"
__author__ = "shalev"
__author_email__ = "contact@lulav.space"
__license__ = "LICENSE"
__copyright__ = "Copyright 2023 Lulav Space"
