
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-18T12:02:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f37dc2584ac7d5efa911ae2ffaadfd63b52f0c9",
 "version": "2023.12.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
