# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_correctiveactions_testbed_build_number_status.get.operation import GetTestbedCasByBuildNumberApiV1CorrectiveactionsTestbedBuildNumberStatusGet
from ahs_orchestator_client.paths.api_v1_correctiveactions_testbed_testbed_id_run.post.operation import TriggerCasBuildWithTestbedIdAndGetBuildNumberApiV1CorrectiveactionsTestbedTestbedIdRunPost
from ahs_orchestator_client.paths.api_v1_correctiveactions_testbed_testbed_id.get.operation import CheckCasByTestbedIdApiV1CorrectiveactionsTestbedTestbedIdGet


class CorrectiveActionsApi(
    GetTestbedCasByBuildNumberApiV1CorrectiveactionsTestbedBuildNumberStatusGet,
    TriggerCasBuildWithTestbedIdAndGetBuildNumberApiV1CorrectiveactionsTestbedTestbedIdRunPost,
    CheckCasByTestbedIdApiV1CorrectiveactionsTestbedTestbedIdGet,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
