
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-20T20:26:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5550dc00f2a3819c6cf56ebfd3139fbcb2048bf9",
 "version": "3.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
