# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_metric_metric_testbed_testbed_id.get.operation import ApiForGet


class ApiV1MetricMetricTestbedTestbedId(
    ApiForGet,
):
    pass
