# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_casfirmware.get.operation import GetCasFirmwareApiV1CasfirmwareGet


class CasFirmwareApi(
    GetCasFirmwareApiV1CasfirmwareGet,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
