# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_health.get.operation import HealthApiV1HealthGet
from ahs_orchestator_client.paths.api_v1_health_env.get.operation import HealthApiV1HealthEnvGet


class HealthApi(
    HealthApiV1HealthGet,
    HealthApiV1HealthEnvGet,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
