# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_healthchekssequence_health_check_definition_id.get.operation import ApiForGet


class ApiV1HealthchekssequenceHealthCheckDefinitionId(
    ApiForGet,
):
    pass
