
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-20T16:58:57-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a2482d058275f5042fe15129fb08bb6b1ae7a8d",
 "version": "2.14.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
