"""Module containing package information for setup.py and __init__.py"""
__title__ = "eumdac"
__description__ = "EUMETSAT Data Access Client"
__url__ = "https://gitlab.eumetsat.int/eumetlab/data-services/eumdac"
__version__ = "2.2.1"
__documentation__ = "https://eumetsatspace.atlassian.net/wiki/spaces/EUMDAC"
__author__ = "EUMETSAT"
__author_email__ = "ops@eumetsat.int"
__license__ = "MIT"
