# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_nums.ipynb.

# %% auto 0
__all__ = ['intq', 'floatq', 'real', 'reals', 'realq', 'num', 'nums', 'numq', 'numstr']

# %% ../nbs/02_nums.ipynb 6
#| export


# %% ../nbs/02_nums.ipynb 8
#| export


# %% ../nbs/02_nums.ipynb 10
#| export


# %% ../nbs/02_nums.ipynb 12
from ptyp import Alias, Opt
from itry import number

# %% ../nbs/02_nums.ipynb 14
#| export


# %% ../nbs/02_nums.ipynb 16
@Opt(int)
class intq: '''int or None'''


@Opt(float)
class floatq: '''float or None'''

# %% ../nbs/02_nums.ipynb 18
@Alias(int, float)
class real: '''R (i.e. int or float)'''

@Alias(list, attrs=dict(dtype=real))
class reals: '''list of `real`'''

@Opt(real)
class realq: '''real or None'''

# %% ../nbs/02_nums.ipynb 19
@Alias(int, float, complex, number)
class num: '''int, float, complex, Number'''

@Alias(list, attrs=dict(dtype=num))
class nums: '''list of `num`'''

@Opt(num)
class numq: '''num or None'''

# %% ../nbs/02_nums.ipynb 20
@Alias(num, str)
class numstr: '''`num` or str'''
