
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-18T18:30:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "133b1078e36559bdc600fb1783599db5c68f177c",
 "version": "2.7.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
