
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-20T11:31:36-0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "80bb89d89af424770bd58ccbc3784a69bce10961",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
