
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-22T17:58:59+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0bf90da2d27ff6ce73548bd1658f341275cb8e93",
 "version": "0.7.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
