# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_jenkins_queue_queue_id.get.operation import ApiForGet


class ApiV1JenkinsQueueQueueId(
    ApiForGet,
):
    pass
