# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_correctiveactions_testbed_build_number_status.get.operation import ApiForGet


class ApiV1CorrectiveactionsTestbedBuildNumberStatus(
    ApiForGet,
):
    pass
