#!/usr/bin/env python

"""Tests for `pattern_analysis` package."""

import pytest


from pattern_analysis import pattern_analysis


ori = "ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTTGTATCTCCTTCCTCTCGTACTCTCATGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTCAGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCATCACTGACTAGCCAAAGCCTTACTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCAATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC"

pat1 = "TGATCA"

pat2 = "TTT"

def test_pattern_count():
    assert pattern_analysis.pattern_count(Text=ori, Pattern=pat1)==8
    assert pattern_analysis.pattern_count(Text=ori, Pattern=pat2)==16

mapping = {
    'A': 'T',
    'T': 'A',
    'G': 'C',
    'C': 'G'
}

def test_pattern_complement():
    assert pattern_analysis.pattern_complement("ATCGTTCG")=="TAGCAAGC"
    assert pattern_analysis.pattern_complement("GTCCATG")=="CAGGTAC"
