
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-21T15:18:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad8b1af5f81e693677cb07e75b4cedc39954a3b5",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
