# Autogenerated by devscripts/update-version.py

__version__ = '2023.12.19.232701'

RELEASE_GIT_HEAD = 'db8b4edc7d0bd27da462f6fe82ff6e13e3d68a04'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2023.12.19.232701dev'
