
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-20T19:40:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f155ed2edd725540e2374cbf63e9ead25b164691",
 "version": "8.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
