from .base_model import BaseModel

class CompanyStructure():
    _ID = '_id'
    ID = 'id'
    NAME = 'name'
    BRANCHES = 'branches'
    DESCRIPTION = 'description'
    OPERATION = 'operation'
    LOGO = 'logo'
    TAX_IDENTIFICATION_NUMBER = 'tax_identification_number'
    LICENSE_TIME = 'license_time'
    ACTIVE_TIME = 'active_time'
    LEGAL_REPRESENTATIVE = 'legal_representative'
    OWNER_OF_COMPANY = 'owner_of_company'
    HEADQUARTER = 'headquarter'
    WEBSITES = 'websites'
    PROFILES_CONTACT = 'profiles_contact'
    EMAIL = 'email'
    OTHER_EMAIL = 'other_email'
    PHONE_NUMBER = 'phone_number'
    OTHER_PHONE_NUMBER = 'other_phone_number'
    UPDATED_TIME = 'updated_time'
    CREATED_TIME = 'created_time'
    STAFF_ID = 'staff_id'
    MERCHANT_ID = 'merchant_id'
    STATUS = 'status'
    DELETED_TIME = 'deleted_time'
    SOURCE_CREATE = 'source_create'
    SCHEDULE_ID = 'schedule_id'
    SCOPE_CODE = 'scope_code'
    SOURCE_COMPANY_ID = 'source_company_id'
    COUNTRY_CODE = 'country_code'
    PROVINCE_CODE = 'province_code'
    DISTRICT_CODE = 'district_code'
    WARD_CODE = 'ward_code'
    ADDRESS = 'address'
    ADDRESS_TYPE = 'address_type'
    ADDRESS_DETAIL = 'address_detail'
    TAX_CODE_ISSUER = 'tax_code_issuer'
    MAIN_BUSINESS = 'main_business'
    GROUP_FINANCE_INFORMATION = 'group_finance_information'
    PROFILES = 'profiles'
    CIF = 'cif'
    SOURCE = 'source'


class Company(BaseModel):
    collection_name = 'company'