
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-22T14:00:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b67ef5899b5fec830e49a03a22272cb5a9ff6aba",
 "version": "3.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
