# coding: utf-8

"""
    Seeq REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 58.8.8-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class DetailedTimerOutputV1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'durations': 'list[int]',
        'path': 'str'
    }

    attribute_map = {
        'description': 'description',
        'durations': 'durations',
        'path': 'path'
    }

    def __init__(self, description=None, durations=None, path=None):
        """
        DetailedTimerOutputV1 - a model defined in Swagger
        """

        self._description = None
        self._durations = None
        self._path = None

        if description is not None:
          self.description = description
        if durations is not None:
          self.durations = durations
        if path is not None:
          self.path = path

    @property
    def description(self):
        """
        Gets the description of this DetailedTimerOutputV1.
        Human readable description of the facet of the system being monitored.

        :return: The description of this DetailedTimerOutputV1.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this DetailedTimerOutputV1.
        Human readable description of the facet of the system being monitored.

        :param description: The description of this DetailedTimerOutputV1.
        :type: str
        """

        self._description = description

    @property
    def durations(self):
        """
        Gets the durations of this DetailedTimerOutputV1.
        Durations in nanoseconds where each value represents one occurrence of a timed event. The values may increase if the timed event is still in progress.

        :return: The durations of this DetailedTimerOutputV1.
        :rtype: list[int]
        """
        return self._durations

    @durations.setter
    def durations(self, durations):
        """
        Sets the durations of this DetailedTimerOutputV1.
        Durations in nanoseconds where each value represents one occurrence of a timed event. The values may increase if the timed event is still in progress.

        :param durations: The durations of this DetailedTimerOutputV1.
        :type: list[int]
        """

        self._durations = durations

    @property
    def path(self):
        """
        Gets the path of this DetailedTimerOutputV1.
        Unique ID for the monitored value.

        :return: The path of this DetailedTimerOutputV1.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this DetailedTimerOutputV1.
        Unique ID for the monitored value.

        :param path: The path of this DetailedTimerOutputV1.
        :type: str
        """

        self._path = path

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DetailedTimerOutputV1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
