
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-20T17:08:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d32ebefa0af4d6266fc847c99906f446dfc455e",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
