# coding: utf-8

"""
    Event Ingestion API

    Event Ingestion API client for DataKitchen’s DataOps Observability  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@datakitchen.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import events_ingestion_client
from events_ingestion_client.models.testgen_table_group_v1_schema import TestgenTableGroupV1Schema  # noqa: E501
from events_ingestion_client.rest import ApiException


class TestTestgenTableGroupV1Schema(unittest.TestCase):
    """TestgenTableGroupV1Schema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestgenTableGroupV1Schema(self):
        """Test TestgenTableGroupV1Schema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = events_ingestion_client.models.testgen_table_group_v1_schema.TestgenTableGroupV1Schema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
