__name__ = 'easyphysi'
__version__ = '1.0.0'
__summary__ = 'Physics library to solve pre-universitary physics problems'
__author__ = 'Carles Mesado'
__email__ = 'mesado31@gmail.com'
__dependencies__ = 'matplotlib, sympy, scipy'
