#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2305-31-g16e4a6e3"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2305
#define NETGEN_VERSION_TWEAK 31
#define NETGEN_VERSION_HASH "g16e4a6e3"
#endif // NETGEN_VERSION_HPP_INCLUDED
