# Generated by Django 3.2.9 on 2023-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simo_nuki', '0004_auto_20231006_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='nukidevice',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='nukidevice',
            name='port',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nukidevice',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
