# Version file autogenerated by the build process
version = '0.13.8'
build = 1304
vcs_info = 'Git SHA1 c14d3a96 committed on 2023-12-18'
package_name = 'ksconf'

SHELL_VER_VARS = 'KSCONF_VERSION="0.13.8"\nKSCONF_BUILD="1304"\nKSCONF_VCS_INFO="Git SHA1 c14d3a96 committed on 2023-12-18"'

if __name__ == '__main__':
    print("# Please use 'python -m ksconf.version' instead.  This will eventually go away.")
    print(SHELL_VER_VARS)
