# Generated by Django 3.2.9 on 2023-10-06 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simo_nuki', '0003_auto_20231006_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='nukidevice',
            name='last_state_data',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='nukidevice',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nukidevice',
            name='last_state',
            field=models.CharField(max_length=50),
        ),
    ]
