# coding: utf-8

"""
    Carrier API

    **Seaplane Global Messaging Service**  For information about authentication see [authentication](/docs/authentication)   # noqa: E501

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@seaplane.io
    Generated by: https://openapi-generator.tech
"""

from seaplane_framework.api.paths.kv_kv_store.put import CreateStore
from seaplane_framework.api.paths.kv_kv_store_key_key.delete import DeleteKey
from seaplane_framework.api.paths.kv_kv_store.delete import DeleteStore
from seaplane_framework.api.paths.kv_kv_store_key_key.get import GetKey
from seaplane_framework.api.paths.kv_kv_store.get import GetStore
from seaplane_framework.api.paths.kv_kv_store_key.get import ListKeys
from seaplane_framework.api.paths.kv.get import ListStores
from seaplane_framework.api.paths.kv_kv_store_key_key.put import PutKey


class KeyValueApi(
    CreateStore,
    DeleteKey,
    DeleteStore,
    GetKey,
    GetStore,
    ListKeys,
    ListStores,
    PutKey,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
