# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansys/api/fluent/v0/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ansys/api/fluent/v0/events.proto\x12\x0cgrpcRemoting\"\x17\n\x15\x42\x65ginStreamingRequest\"1\n\x12TimestepEndedEvent\x12\r\n\x05index\x18\x01 \x01(\x12\x12\x0c\n\x04size\x18\x02 \x01(\x01\"$\n\x13IterationEndedEvent\x12\r\n\x05index\x18\x01 \x01(\x12\"\x1a\n\x18\x43\x61lculationsStartedEvent\"\x18\n\x16\x43\x61lculationsEndedEvent\",\n\x14\x41\x62outToReadCaseEvent\x12\x14\n\x0c\x63\x61sefilepath\x18\x01 \x01(\t\"%\n\rCaseReadEvent\x12\x14\n\x0c\x63\x61sefilepath\x18\x01 \x01(\t\"%\n\rDataReadEvent\x12\x14\n\x0c\x64\x61tafilepath\x18\x01 \x01(\t\"\x12\n\x10InitializedEvent\"9\n\rProgressEvent\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0fpercentComplete\x18\x02 \x01(\x11\"0\n\nErrorEvent\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\terrorCode\x18\x02 \x01(\x11\"\x86\x05\n\x16\x42\x65ginStreamingResponse\x12\x42\n\x14\x61\x62outtoreadcaseevent\x18\x01 \x01(\x0b\x32\".grpcRemoting.AboutToReadCaseEventH\x00\x12\x34\n\rcasereadevent\x18\x02 \x01(\x0b\x32\x1b.grpcRemoting.CaseReadEventH\x00\x12:\n\x10initializedevent\x18\x04 \x01(\x0b\x32\x1e.grpcRemoting.InitializedEventH\x00\x12\x34\n\rdatareadevent\x18\x06 \x01(\x0b\x32\x1b.grpcRemoting.DataReadEventH\x00\x12@\n\x13iterationendedevent\x18\x08 \x01(\x0b\x32!.grpcRemoting.IterationEndedEventH\x00\x12>\n\x12timestependedevent\x18\n \x01(\x0b\x32 .grpcRemoting.TimestepEndedEventH\x00\x12J\n\x18\x63\x61lculationsstartedevent\x18\x0b \x01(\x0b\x32&.grpcRemoting.CalculationsStartedEventH\x00\x12\x46\n\x16\x63\x61lculationsendedevent\x18\x0c \x01(\x0b\x32$.grpcRemoting.CalculationsEndedEventH\x00\x12\x34\n\rprogressevent\x18\x14 \x01(\x0b\x32\x1b.grpcRemoting.ProgressEventH\x00\x12.\n\nerrorevent\x18\x15 \x01(\x0b\x32\x18.grpcRemoting.ErrorEventH\x00\x42\x04\n\x02\x61s2i\n\x06\x45vents\x12_\n\x0e\x42\x65ginStreaming\x12#.grpcRemoting.BeginStreamingRequest\x1a$.grpcRemoting.BeginStreamingResponse\"\x00\x30\x01\x62\x06proto3')



_BEGINSTREAMINGREQUEST = DESCRIPTOR.message_types_by_name['BeginStreamingRequest']
_TIMESTEPENDEDEVENT = DESCRIPTOR.message_types_by_name['TimestepEndedEvent']
_ITERATIONENDEDEVENT = DESCRIPTOR.message_types_by_name['IterationEndedEvent']
_CALCULATIONSSTARTEDEVENT = DESCRIPTOR.message_types_by_name['CalculationsStartedEvent']
_CALCULATIONSENDEDEVENT = DESCRIPTOR.message_types_by_name['CalculationsEndedEvent']
_ABOUTTOREADCASEEVENT = DESCRIPTOR.message_types_by_name['AboutToReadCaseEvent']
_CASEREADEVENT = DESCRIPTOR.message_types_by_name['CaseReadEvent']
_DATAREADEVENT = DESCRIPTOR.message_types_by_name['DataReadEvent']
_INITIALIZEDEVENT = DESCRIPTOR.message_types_by_name['InitializedEvent']
_PROGRESSEVENT = DESCRIPTOR.message_types_by_name['ProgressEvent']
_ERROREVENT = DESCRIPTOR.message_types_by_name['ErrorEvent']
_BEGINSTREAMINGRESPONSE = DESCRIPTOR.message_types_by_name['BeginStreamingResponse']
BeginStreamingRequest = _reflection.GeneratedProtocolMessageType('BeginStreamingRequest', (_message.Message,), {
  'DESCRIPTOR' : _BEGINSTREAMINGREQUEST,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.BeginStreamingRequest)
  })
_sym_db.RegisterMessage(BeginStreamingRequest)

TimestepEndedEvent = _reflection.GeneratedProtocolMessageType('TimestepEndedEvent', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTEPENDEDEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.TimestepEndedEvent)
  })
_sym_db.RegisterMessage(TimestepEndedEvent)

IterationEndedEvent = _reflection.GeneratedProtocolMessageType('IterationEndedEvent', (_message.Message,), {
  'DESCRIPTOR' : _ITERATIONENDEDEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.IterationEndedEvent)
  })
_sym_db.RegisterMessage(IterationEndedEvent)

CalculationsStartedEvent = _reflection.GeneratedProtocolMessageType('CalculationsStartedEvent', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATIONSSTARTEDEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.CalculationsStartedEvent)
  })
_sym_db.RegisterMessage(CalculationsStartedEvent)

CalculationsEndedEvent = _reflection.GeneratedProtocolMessageType('CalculationsEndedEvent', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATIONSENDEDEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.CalculationsEndedEvent)
  })
_sym_db.RegisterMessage(CalculationsEndedEvent)

AboutToReadCaseEvent = _reflection.GeneratedProtocolMessageType('AboutToReadCaseEvent', (_message.Message,), {
  'DESCRIPTOR' : _ABOUTTOREADCASEEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.AboutToReadCaseEvent)
  })
_sym_db.RegisterMessage(AboutToReadCaseEvent)

CaseReadEvent = _reflection.GeneratedProtocolMessageType('CaseReadEvent', (_message.Message,), {
  'DESCRIPTOR' : _CASEREADEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.CaseReadEvent)
  })
_sym_db.RegisterMessage(CaseReadEvent)

DataReadEvent = _reflection.GeneratedProtocolMessageType('DataReadEvent', (_message.Message,), {
  'DESCRIPTOR' : _DATAREADEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.DataReadEvent)
  })
_sym_db.RegisterMessage(DataReadEvent)

InitializedEvent = _reflection.GeneratedProtocolMessageType('InitializedEvent', (_message.Message,), {
  'DESCRIPTOR' : _INITIALIZEDEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.InitializedEvent)
  })
_sym_db.RegisterMessage(InitializedEvent)

ProgressEvent = _reflection.GeneratedProtocolMessageType('ProgressEvent', (_message.Message,), {
  'DESCRIPTOR' : _PROGRESSEVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.ProgressEvent)
  })
_sym_db.RegisterMessage(ProgressEvent)

ErrorEvent = _reflection.GeneratedProtocolMessageType('ErrorEvent', (_message.Message,), {
  'DESCRIPTOR' : _ERROREVENT,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.ErrorEvent)
  })
_sym_db.RegisterMessage(ErrorEvent)

BeginStreamingResponse = _reflection.GeneratedProtocolMessageType('BeginStreamingResponse', (_message.Message,), {
  'DESCRIPTOR' : _BEGINSTREAMINGRESPONSE,
  '__module__' : 'ansys.api.fluent.v0.events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.BeginStreamingResponse)
  })
_sym_db.RegisterMessage(BeginStreamingResponse)

_EVENTS = DESCRIPTOR.services_by_name['Events']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BEGINSTREAMINGREQUEST._serialized_start=50
  _BEGINSTREAMINGREQUEST._serialized_end=73
  _TIMESTEPENDEDEVENT._serialized_start=75
  _TIMESTEPENDEDEVENT._serialized_end=124
  _ITERATIONENDEDEVENT._serialized_start=126
  _ITERATIONENDEDEVENT._serialized_end=162
  _CALCULATIONSSTARTEDEVENT._serialized_start=164
  _CALCULATIONSSTARTEDEVENT._serialized_end=190
  _CALCULATIONSENDEDEVENT._serialized_start=192
  _CALCULATIONSENDEDEVENT._serialized_end=216
  _ABOUTTOREADCASEEVENT._serialized_start=218
  _ABOUTTOREADCASEEVENT._serialized_end=262
  _CASEREADEVENT._serialized_start=264
  _CASEREADEVENT._serialized_end=301
  _DATAREADEVENT._serialized_start=303
  _DATAREADEVENT._serialized_end=340
  _INITIALIZEDEVENT._serialized_start=342
  _INITIALIZEDEVENT._serialized_end=360
  _PROGRESSEVENT._serialized_start=362
  _PROGRESSEVENT._serialized_end=419
  _ERROREVENT._serialized_start=421
  _ERROREVENT._serialized_end=469
  _BEGINSTREAMINGRESPONSE._serialized_start=472
  _BEGINSTREAMINGRESPONSE._serialized_end=1118
  _EVENTS._serialized_start=1120
  _EVENTS._serialized_end=1225
# @@protoc_insertion_point(module_scope)
