"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class BeginStreamingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___BeginStreamingRequest = BeginStreamingRequest

class TimestepEndedEvent(google.protobuf.message.Message):
    """*
    Event at end of the time step.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INDEX_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    index: builtins.int = ...
    """Time step index."""

    size: builtins.float = ...
    """Time step size."""

    def __init__(self,
        *,
        index : builtins.int = ...,
        size : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["index",b"index","size",b"size"]) -> None: ...
global___TimestepEndedEvent = TimestepEndedEvent

class IterationEndedEvent(google.protobuf.message.Message):
    """*
    Event at end of the iteration.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INDEX_FIELD_NUMBER: builtins.int
    index: builtins.int = ...
    """Iteration index"""

    def __init__(self,
        *,
        index : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["index",b"index"]) -> None: ...
global___IterationEndedEvent = IterationEndedEvent

class CalculationsStartedEvent(google.protobuf.message.Message):
    """*
    Event at start of calculation.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___CalculationsStartedEvent = CalculationsStartedEvent

class CalculationsEndedEvent(google.protobuf.message.Message):
    """*
    Event at end of calculation.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___CalculationsEndedEvent = CalculationsEndedEvent

class AboutToReadCaseEvent(google.protobuf.message.Message):
    """*
    Event at start of case read.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CASEFILEPATH_FIELD_NUMBER: builtins.int
    casefilepath: typing.Text = ...
    """Case file path."""

    def __init__(self,
        *,
        casefilepath : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["casefilepath",b"casefilepath"]) -> None: ...
global___AboutToReadCaseEvent = AboutToReadCaseEvent

class CaseReadEvent(google.protobuf.message.Message):
    """*
    Event after case is read.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CASEFILEPATH_FIELD_NUMBER: builtins.int
    casefilepath: typing.Text = ...
    """Case file path."""

    def __init__(self,
        *,
        casefilepath : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["casefilepath",b"casefilepath"]) -> None: ...
global___CaseReadEvent = CaseReadEvent

class DataReadEvent(google.protobuf.message.Message):
    """*
    Event at data read.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATAFILEPATH_FIELD_NUMBER: builtins.int
    datafilepath: typing.Text = ...
    """Data file path."""

    def __init__(self,
        *,
        datafilepath : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["datafilepath",b"datafilepath"]) -> None: ...
global___DataReadEvent = DataReadEvent

class InitializedEvent(google.protobuf.message.Message):
    """*
    Event at solution initialization.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___InitializedEvent = InitializedEvent

class ProgressEvent(google.protobuf.message.Message):
    """*
    Event during solution progress.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_FIELD_NUMBER: builtins.int
    PERCENTCOMPLETE_FIELD_NUMBER: builtins.int
    message: typing.Text = ...
    """Progress Message."""

    percentComplete: builtins.int = ...
    """Percent completed."""

    def __init__(self,
        *,
        message : typing.Text = ...,
        percentComplete : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message","percentComplete",b"percentComplete"]) -> None: ...
global___ProgressEvent = ProgressEvent

class ErrorEvent(google.protobuf.message.Message):
    """
    Event when fatal error encountered
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_FIELD_NUMBER: builtins.int
    ERRORCODE_FIELD_NUMBER: builtins.int
    message: typing.Text = ...
    errorCode: builtins.int = ...
    def __init__(self,
        *,
        message : typing.Text = ...,
        errorCode : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["errorCode",b"errorCode","message",b"message"]) -> None: ...
global___ErrorEvent = ErrorEvent

class BeginStreamingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ABOUTTOREADCASEEVENT_FIELD_NUMBER: builtins.int
    CASEREADEVENT_FIELD_NUMBER: builtins.int
    INITIALIZEDEVENT_FIELD_NUMBER: builtins.int
    DATAREADEVENT_FIELD_NUMBER: builtins.int
    ITERATIONENDEDEVENT_FIELD_NUMBER: builtins.int
    TIMESTEPENDEDEVENT_FIELD_NUMBER: builtins.int
    CALCULATIONSSTARTEDEVENT_FIELD_NUMBER: builtins.int
    CALCULATIONSENDEDEVENT_FIELD_NUMBER: builtins.int
    PROGRESSEVENT_FIELD_NUMBER: builtins.int
    ERROREVENT_FIELD_NUMBER: builtins.int
    @property
    def abouttoreadcaseevent(self) -> global___AboutToReadCaseEvent: ...
    @property
    def casereadevent(self) -> global___CaseReadEvent: ...
    @property
    def initializedevent(self) -> global___InitializedEvent: ...
    @property
    def datareadevent(self) -> global___DataReadEvent: ...
    @property
    def iterationendedevent(self) -> global___IterationEndedEvent: ...
    @property
    def timestependedevent(self) -> global___TimestepEndedEvent: ...
    @property
    def calculationsstartedevent(self) -> global___CalculationsStartedEvent: ...
    @property
    def calculationsendedevent(self) -> global___CalculationsEndedEvent: ...
    @property
    def progressevent(self) -> global___ProgressEvent: ...
    @property
    def errorevent(self) -> global___ErrorEvent: ...
    def __init__(self,
        *,
        abouttoreadcaseevent : typing.Optional[global___AboutToReadCaseEvent] = ...,
        casereadevent : typing.Optional[global___CaseReadEvent] = ...,
        initializedevent : typing.Optional[global___InitializedEvent] = ...,
        datareadevent : typing.Optional[global___DataReadEvent] = ...,
        iterationendedevent : typing.Optional[global___IterationEndedEvent] = ...,
        timestependedevent : typing.Optional[global___TimestepEndedEvent] = ...,
        calculationsstartedevent : typing.Optional[global___CalculationsStartedEvent] = ...,
        calculationsendedevent : typing.Optional[global___CalculationsEndedEvent] = ...,
        progressevent : typing.Optional[global___ProgressEvent] = ...,
        errorevent : typing.Optional[global___ErrorEvent] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["abouttoreadcaseevent",b"abouttoreadcaseevent","as",b"as","calculationsendedevent",b"calculationsendedevent","calculationsstartedevent",b"calculationsstartedevent","casereadevent",b"casereadevent","datareadevent",b"datareadevent","errorevent",b"errorevent","initializedevent",b"initializedevent","iterationendedevent",b"iterationendedevent","progressevent",b"progressevent","timestependedevent",b"timestependedevent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["abouttoreadcaseevent",b"abouttoreadcaseevent","as",b"as","calculationsendedevent",b"calculationsendedevent","calculationsstartedevent",b"calculationsstartedevent","casereadevent",b"casereadevent","datareadevent",b"datareadevent","errorevent",b"errorevent","initializedevent",b"initializedevent","iterationendedevent",b"iterationendedevent","progressevent",b"progressevent","timestependedevent",b"timestependedevent"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["as",b"as"]) -> typing.Optional[typing_extensions.Literal["abouttoreadcaseevent","casereadevent","initializedevent","datareadevent","iterationendedevent","timestependedevent","calculationsstartedevent","calculationsendedevent","progressevent","errorevent"]]: ...
global___BeginStreamingResponse = BeginStreamingResponse
