from enum import Enum


class DeveloperErrorErrorKind(str, Enum):
    ASSERTION_FAILED = "ASSERTION_FAILED"
    DUPLICATE_RELATIONSHIP = "DUPLICATE_RELATIONSHIP"
    EXTRA_RELATIONSHIP_FOUND = "EXTRA_RELATIONSHIP_FOUND"
    MAXIMUM_RECURSION = "MAXIMUM_RECURSION"
    MISSING_EXPECTED_RELATIONSHIP = "MISSING_EXPECTED_RELATIONSHIP"
    PARSE_ERROR = "PARSE_ERROR"
    SCHEMA_ISSUE = "SCHEMA_ISSUE"
    UNKNOWN_KIND = "UNKNOWN_KIND"
    UNKNOWN_OBJECT_TYPE = "UNKNOWN_OBJECT_TYPE"
    UNKNOWN_RELATION = "UNKNOWN_RELATION"

    def __str__(self) -> str:
        return str(self.value)
