
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-20T19:28:38+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "93e26dfdc0324a0c21fb310aa995cd85f4ed0fef",
 "version": "0.8.0.post0.dev15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
