#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2305-29-ga272a8d4"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2305
#define NETGEN_VERSION_TWEAK 29
#define NETGEN_VERSION_HASH "ga272a8d4"
#endif // NETGEN_VERSION_HPP_INCLUDED
