
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-18T14:27:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0094ff09c49b7ea831b655a17fdd2ea734d54a36",
 "version": "2.7.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
