# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from ahs_orchestator_client.paths.api_v1_testbed_status.post.operation import ApiForPost


class ApiV1TestbedStatus(
    ApiForPost,
):
    pass
