# Autogenerated by devscripts/update-version.py

__version__ = '2023.12.20.232717'

RELEASE_GIT_HEAD = '37755a037e612bfc608c3d4722e8ef2ce6a022ee'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2023.12.20.232717dev'
