# Generated by Django 4.2.3 on 2023-12-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0008_dietplan_dietplanfood_dietplanfoodevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='first_day_diet_id',
        ),
        migrations.RemoveField(
            model_name='dietplanfood',
            name='day_diet_food_id',
        ),
        migrations.RemoveField(
            model_name='dietplanfoodevent',
            name='backfill_id',
        ),
        migrations.RemoveField(
            model_name='dietplanfoodeventlog',
            name='backfill_id',
        ),
    ]
