# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .acl_role import *
from .acl_rule import *
from .acl_user import *
from .active_active_subscription import *
from .active_active_subscription_database import *
from .active_active_subscription_peering import *
from .active_active_subscription_regions import *
from .cloud_account import *
from .get_acl_role import *
from .get_acl_rule import *
from .get_acl_user import *
from .get_cloud_account import *
from .get_data_persistence import *
from .get_database import *
from .get_database_modules import *
from .get_payment_method import *
from .get_regions import *
from .get_subscription import *
from .get_subscription_peerings import *
from .provider import *
from .subscription import *
from .subscription_database import *
from .subscription_peering import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_rediscloud.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_rediscloud.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "rediscloud",
  "mod": "index/aclRole",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/aclRole:AclRole": "AclRole"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/aclRule",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/aclRule:AclRule": "AclRule"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/aclUser",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/aclUser:AclUser": "AclUser"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/activeActiveSubscription",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/activeActiveSubscription:ActiveActiveSubscription": "ActiveActiveSubscription"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/activeActiveSubscriptionDatabase",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/activeActiveSubscriptionDatabase:ActiveActiveSubscriptionDatabase": "ActiveActiveSubscriptionDatabase"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/activeActiveSubscriptionPeering",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/activeActiveSubscriptionPeering:ActiveActiveSubscriptionPeering": "ActiveActiveSubscriptionPeering"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/activeActiveSubscriptionRegions",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/activeActiveSubscriptionRegions:ActiveActiveSubscriptionRegions": "ActiveActiveSubscriptionRegions"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/cloudAccount",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/cloudAccount:CloudAccount": "CloudAccount"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/subscription",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/subscription:Subscription": "Subscription"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/subscriptionDatabase",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/subscriptionDatabase:SubscriptionDatabase": "SubscriptionDatabase"
  }
 },
 {
  "pkg": "rediscloud",
  "mod": "index/subscriptionPeering",
  "fqn": "pulumi_rediscloud",
  "classes": {
   "rediscloud:index/subscriptionPeering:SubscriptionPeering": "SubscriptionPeering"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "rediscloud",
  "token": "pulumi:providers:rediscloud",
  "fqn": "pulumi_rediscloud",
  "class": "Provider"
 }
]
"""
)
